### ISSUE TITLE
Cannot select path on Ubuntu 22.04

### ISSUE THREAD

**Issue by Hannah-GBS** [dsymbol/yt-dlp-gui#17]
Ubuntu 22.04.2, 64-bit, using the portable Linux release from 25.05.2023.

Clicking the Path selector button (3 dots) instantly closes the program.

**Comment by dsymbol** [comment]
It seems like the problem is caused by Ubuntu 22.04.2 using Wayland. I faced similar issues with the this release, but I managed to resolve them by [building](https://github.com/dsymbol/yt-dlp-gui#build) it on my own system from source. You might want to try doing the same. I'm considering discontinuing Linux builds altogether because they can be quite complicated and don't work universally.
