### ISSUE TITLE
Virus Total Detection

### ISSUE THREAD

**Issue by Tomas683** [dsymbol/yt-dlp-gui#6]
Hey guys I'm sure its not anything serious but I got 3 detections on virus total, specifically from the yt-dlp-gui.exe file. Can anyone explain what this might be?

**Comment by dsymbol** [comment]
False positives due to pyinstaller see [[1]](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md) [[2]](https://github.com/pyinstaller/pyinstaller/issues?q=label%3Aantivirus-false-positives).
Not much I can do about it but you can [build](https://github.com/dsymbol/yt-dlp-gui#build) the program yourself.
